add-controllers
Bervy/java-shareit pull request #1
Opened 2022-10-17 11:59 UTC by Bervy

add : Added item and user controllers and layers to implement their endpoints

2022-10-17 17:27 UTC, Frilock requested changes
Добрый вечер, в целом нормальная работа, пара небольших комментариев к ней.

2022-10-17 17:27 UTC, Frilock commented on pom.xml
> +			<version>1.13</version>
А почему эту версию в properties не вынесли? Не сталкивался с такой либой, а чем стандартный метод не подошел?

2022-10-17 17:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +@Slf4j
Не лишняя? Не вижу использования

2022-10-17 17:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/impl/ItemDaoImpl.java
> +        if (items.containsKey(itemId)) {
2 if можно обьединить, тогда бросок исключения будет 1

2022-10-17 17:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/impl/ItemDaoImpl.java
> +                .filter(item -> item.getName().toLowerCase().contains(text.toLowerCase()) ||
item.getName null не вернет?

2022-10-17 17:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if (itemDto.getName().equals("")) {
А почему такая проверка странная? Почему не через Onjects.isNotBlank? Проверит условие, что поле не пустое и что != null. Для других аналогичных ситуация, я бы тоже его советовал использовать

2022-10-17 17:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserDaoImpl.java
> +
Лишняя строчка

2022-10-17 17:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserCrudService.java
> +@Service
Странно, тут вы вешаете аннотацию, а например, UserFindService тут нет. В чем логика? по идее над интерфейсом можно не вешать аннотацию, достаточно над реализацией.

2022-10-17 17:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        if (userDto.getEmail() == null) {
Слабоватая проверка для email, лучше через регулярку (регулярное выражение) проверять

2022-10-18 07:13 UTC, Bervy commented on pom.xml
> +			<version>1.13</version>
Убрал библиотеку

2022-10-18 07:21 UTC, Bervy commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +@Slf4j
Убрал

2022-10-18 07:23 UTC, Bervy commented on src/main/java/ru/practicum/shareit/item/repository/impl/ItemDaoImpl.java
> +        if (items.containsKey(itemId)) {
Но ведь в одном случае нету владельца, а в другом вещи.

2022-10-18 07:25 UTC, Bervy commented on src/main/java/ru/practicum/shareit/item/repository/impl/ItemDaoImpl.java
> +                .filter(item -> item.getName().toLowerCase().contains(text.toLowerCase()) ||
нет, так как имя всегда должно быть

2022-10-18 07:38 UTC, Bervy commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if (itemDto.getName().equals("")) {
Не нашел такой метод у Objects, использовал StringUtils.isNotBlank и подключил библиотеку для этого

2022-10-18 07:40 UTC, Bervy commented on src/main/java/ru/practicum/shareit/user/service/UserCrudService.java
> +@Service
Убрал аннотацию

2022-10-18 07:44 UTC, Bervy commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        if (userDto.getEmail() == null) {
У меня же есть аннотация есть email в userDto

2022-10-19 06:07 UTC, Frilock approved these changes
Принял

2022-10-30 10:28 UTC, merged