add : added the ability to book
Bervy/java-shareit pull request #2
Opened 2022-11-06 16:17 UTC by Bervy

2022-11-07 18:11 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    @GetMapping()
Пустые скобки лишние

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingFullDto.java
> +        Long id;
Предлагаю для единообразия модификаторы приватные воткнуть. Все равно геттеры сделали

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "id", nullable = false)
Можно в данном случае Column не ставить

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            "b.start < ?2 and " +
Кажется можно на оператор between заменить, посмотрите в других запросах тоже

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        if (bookingDto.getEnd().isBefore(bookingDto.getStart())) throw new ValidationException(
Вроде бы обсуждали такой момент, что такие конструкции все равно лучше обособлять, хотя конечно минор

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Column(name = "text")
Для строковых полей еще лучше указывать размерность, которую вы задаете в скрипте, чтобы проще было анализировать возможные проблемы

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +    public CommentFullDto addComment(Long authorId, Long itemId, CommentDto dto) {
Давайте в отдельный репозиторий вынесем:
Реализована логика по добавлению нового комментария к вещи в сервисе ItemServiceImpl. Создан интерфейс CommentRepository. Есть проверка, что пользователь, который пишет комментарий, действительно брал вещь в аренду.

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if (booking.getStatus().equals(BookingStatus.APPROVED)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +public interface UserRepository  extends JpaRepository<User, Long> {
Лишний пробел перед extends

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +    public ItemServiceImpl(ItemRepository itemRepository,
Предлагаю тогда тоже добавить RequiredArgsConstructor

2022-11-07 18:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/impl/ItemControllerImpl.java
>  import org.springframework.web.bind.annotation.*;
А почему контроллер с impl на конце?) Давайте уберем, чтобы одинаково было =)

2022-11-08 04:49 UTC, Bervy commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "id", nullable = false)
Я для единообразия сделал

2022-11-08 04:53 UTC, Bervy commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            "b.start < ?2 and " +
Не совсем понял как between сделать, если это 2 разных поля

2022-11-08 04:57 UTC, Bervy commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        if (bookingDto.getEnd().isBefore(bookingDto.getStart())) throw new ValidationException(
Не совсем понял, можно объяснить

2022-11-08 05:07 UTC, Bervy commented on src/main/java/ru/practicum/shareit/item/controller/impl/ItemControllerImpl.java
>  import org.springframework.web.bind.annotation.*;
Потому что же он имплеминтирует интерфейс, так же как и сервис

2022-11-08 05:09 UTC, Bervy commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +    public CommentFullDto addComment(Long authorId, Long itemId, CommentDto dto) {
Вот это не совсем понял

2022-11-08 16:56 UTC, Frilock approved these changes
Добрый вечер, принял, но подумал, подумал, и кажется нет смысла делать интерфейс для каждого контроллера. Ведь сам контроллер мы нигде не инжектим

2022-11-08 16:56 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +public interface BookingController {
Подумал, подумал, и кажется нет смысла делать интерфейс для каждого контроллера. Ведь сам контроллер мы нигде не инжектим

2022-11-19 08:20 UTC, merged