add : add item requests ans tests
Bervy/java-shareit pull request #3
Opened 2022-11-19 08:20 UTC by Bervy

2022-11-19 15:38 UTC, Frilock requested changes
Добрый вечер, в целом по заданию все ок. Не очень понял зачем вы с классов модели удалили equals и hashCode? По поводу тестов есть момент с аннотацией 
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)

Точно ли она нужна Вам в тех тестовых классах, в которых вы ее используете?

2022-11-19 15:38 UTC, Frilock commented on pom.xml
> +			<version>42.2.10</version>
Давайте версию в пропертиес вынесем

2022-11-19 15:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> -    public boolean equals(Object o) {
А зачем удалили?

2022-11-19 15:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +                .stream().map(commentMapper::toCommentFullDto).collect(Collectors.toList()));
лучше 
.map
.collect
так принято переносить

2022-11-19 15:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +
Лишняя строчка пустая

2022-11-19 15:38 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTests.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
А для чего тут Вам эта аннотация, так ли она неоходима?

2022-11-21 06:33 UTC, Bervy commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTests.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
Согласен, не нужна

2022-11-21 06:58 UTC, Bervy commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTests.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
Добавил к единственному методу аннотацию

2022-11-21 18:01 UTC, Frilock approved these changes
Принял, успехов дальше

2022-11-21 18:01 UTC, Frilock commented on src/test/java/ru/practicum/shareit/request/ItemRequestIntegrationTests.java
> +    @DirtiesContext(methodMode = DirtiesContext.MethodMode.AFTER_METHOD)
Вообще я имел ввиду, чтобы вы реализовали методы с afterEach и там данные чистили, но так тоже сойдет

2022-11-30 11:39 UTC, merged